### PR TITLE
make it compile on windows msvc

### PR DESCRIPTION
**Pull request by kysucix**
Modification of code and cmaketo make surfelmeshing compile on windows.

### CODE REVIEW

**Comment by puzzlepaint** [comment]
Thanks!

**Comment by puzzlepaint** [comment]
I made some follow-up changes to make it compile on Linux again, I hope that this didn't break Windows compatibility. I also (hopefully) fixed a rendering issue that I think affected BAD SLAM on Windows and probably affected SurfelMeshing too (this does not happen on the system which I usually use for developing, so I wasn't aware of it, but I noticed it when testing a Linux binary on another system).

**Comment by kysucix** [comment]
Hi, I tried to compile it again with your modifications and it's working perfectly 😄

**Comment by zhangybzbo** [comment]
Hi there, I was trying to compile surfelmeshing on windows recently, but constantly got errors regarding Boost. Wonder if you can help me with it.

What I did:

1. Download Boost from [https://sourceforge.net/projects/boost/files/boost-binaries/](url)
2. Unzip and add it into environment variable PATH
3. Compile in Visual Studio

I got the error message:

```
1> [CMake] CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
1> [CMake]   Could NOT find Boost (missing: serialization filesystem system) (found
1> [CMake]   version "1.66.0")
1> [CMake] Call Stack (most recent call first):
1> [CMake]   C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
1> [CMake]   C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.17/Modules/FindBoost.cmake:2145 (find_package_handle_standard_args)
1> [CMake]   CMakeLists.txt:70 (find_package)
1> [CMake] -- Configuring incomplete, errors occurred!
```

Other dependencies are compiled successfully. Any idea?

**Pull request merged**
